project:
  type: website

website:
  title: "570L Fall 2023"
  reader-mode: true
  navbar:
    background: dark
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Class Code
        menu:
        - href: code_main.qmd
          text: General Resources
        - href: code_lab-00.qmd
          text: Intro Assignment Code
        - href: code_lab-01.qmd
          text: Behavioral Ecology Analysis Code
        - href: code_lab-02.qmd
          text: Biodiversity Analysis Code
      - text: Class Documents
        menu:
        - href: lab_0_intro_assignment.qmd
          text: Intro Assignment
        - href: lab_1_behavioral-ecology.qmd
          text: "Lab 1: Behavioral Urban Ecology"
        - href: lab_2_forest-biodiversity.qmd
          text: "Lab 2: Intermediate Distrubance & Forest Ecology"
        - href: lab_3_community-assemblages.qmd
          text: "Lab 3: Community Assemblages"
        - href: lab_4.qmd
          text: "Lab 4"
        - href: lab_5.qmd
          text: "Lab 5"
        - href: proj_main.qmd
          text: "Independent Projects"
      - href: addtl_resources.qmd
        text: Additional Resources
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    code-fold: false
    code-tools: false
    
execute: 
  warning: false

editor: visual
