---
title: Introductory Assignment
---

Submit all answers as a pdf on blackboard's submission portal.

# Part 1: Background about you (5 points):

### 1.a What made you interested in this course?

### 1.b What skills do you hope to gain through this lab?

### 1.c What are your career goals?

# Part 2: Intro to R

To get some basic familiarity with using R, I want you to make a graph.

Graph fiddler crab carapace width by two sites. The graph should be appropriate for the type of data and display the mean crab carapace width by site. Standard error bars should be available as well.

You can download fiddler crab data which I formatted [here](https://raw.githubusercontent.com/USC-Ecology-Lab/Lab_0_Introduction/main/data/LTER_CrabCarapaces.csv). The data originally comes from the LTER's educational resources page. Just click the link, right-click (or command/control S) and save the data as a .csv file. Note you should be able to open the .csv file using excel.

### BONUS (5 points):

Remake the plot but this time include all sites, not just the two. *hint*: this can be achieved by removing one line of `dplyr` code.
