---
title: Independent Projects
---

The primary objective of this lab course will be for students to pursue a self-led investigation of an ecological hypothesis. Students must propose their own projects which they will pursue over the course of the semester.

# General Guidelines:

-   Students may work in groups up to 3 members or individually
-   Projects should be feasible, clearly organized, and interesting. A common pitfall is to create a project that is too complicated and unable to complete in the limited time of lab. A good experiment should be elegant!
-   Projects will take the bulk of the semester, however there will be several milestones along the way to ensure progress.
-   The projects will incorporate ecological concepts learned throughout the semester.

# Phase 1: Idea generation

The first few weeks of lab will involve individual one-week labs. These will introduce students to field work and working in nearby ecosystems. During these labs students should take some time to think about the lab topic and their surroundings. Ask questions about the ecosystem and think of possible projects on these activities.

Access the project plan guide [here](./docs/2023_GenDoc_ProjectPlanGuide.pdf)

Access the project plan rubric [here](./docs/2023_GenDoc_ProjectPlanRubric.pdf)

# Phase 2: Data Collection & Analysis

Over the course of five weeks, students will collect and analyze their data independently. There is a wide range of resources available to support your efforts. I will help with any field work on request!

# Phase 3: Communication of Results

## Presentations

Students will develop a presentation to communicate their findings to their peers. These presentations will follow a typical format of 8-10 minutes for presentations with 2 minutes for question. Developing clear presentations are a critical skill for any ecologist, whether presenting results at a scientific conference or to a general audience. Keep in mind who will be in the audience when presenting your work!

### General Presentation expectations

Access the rubric [here](./docs/2023_GenDoc_Presentation-Rubric.pdf)

Take a good look through the rubric to know what to expect when formatting your presentation. The grading generally corresponds to how much time you should allocate for each section. In class we will discuss exact elements of how to clearly format your presentation and deliver it well.

Some specific considerations for this class:

-   Presentations will be 8 - 10 minutes long

-   You will present your core results. This may not be all your results (if you did a lot)

-   Figures should be large, with clear axes titles

    -   Whenever you show a new figure, introduce the audience to the axis, including scale and units

-   Most people are not familiar at all with your study. Give lots of background! Often times your actual results may be a fairly small part of the overall presentation when presenting to a broad audience.

-   Discuss statistics, but primarily in the context of the figures and how much weigh should be given to any visual trends

-   Discuss future ways to further the research or possible limitation on the data.

    -   DO NOT JUST STATE "Well there's human error so I may have counted wrong". If discussing limitations, specifically how it could influence the data. For example maybe the study was done in October but the flowering status of a plant is a key feature for identification so you may have overestimated a certain plant, etc.

## Final Papers

Students will write a mini-manuscript to communicate their findings. These should be formatted as a small version of work which would be submitted to an ecological peer-reviewed journal. Writing is a critical skill in aiding your thinking and processing of information. Being able to communicate scientific results clearly in writing is important!

### General Presentation Guidelines

Access the rubric [here](./docs/2023_GenDoc_Paper-Rubric.pdf)

Generally, the grading follows the generalized rubric we've used over the course of the class. However, some specifics which might be useful. Think of these as "minimum" requirements. A good paper should exceed these. For example, you should have tried to address your hypotheses which multiple analyses. You may not find it necessary to share every bit of exploratory data but you should include anything that is useful to advance the story you are trying to tell with your data.

-   5+ pages

```{=html}
<!-- -->
```
-   Formatted as introduction, methods, results, discussion, references. Include an abstract as well!

    -   Abstracts are a 200 word statement which summarizes everything

-   3+ references

    -   Peer-reviewed literature is utilized to place your study in context *both* in the introduction and the discussion. And methods if citing a particular method.

-   2 figures and/or tables. There should be at least one figure however, more will make the paper much, much better.

-   At least one statistical analysis (it should be appropriate).

    -   Many of you will have found null results - no effect even if you expected one. That is OK! just explain in the discussion why you think you observed those results.

-   Written in a general scientific format

    -   Like what is in the papers you read!
